### ISSUE TITLE
依赖收集的问题

### ISSUE THREAD

**Issue by lzldemo** [answershuto/learnVue#11]
const dep = new Dep();

    Object.defineProperty(obj, key, {
        enumerable: true,
        configurable: true,
        get: ()=>{
            if (Dep.target) {
                dep.addSub(Dep.target);  
            }
        },
        set:newVal=> {
            dep.notify();
        }
    })

**Dep.target 是全局的watcher， 假如options.data = {name:'demo', age:12}, 对它进行绑定的话，dep会两次把全局的Watcher  push到自己的subs中，这样重复做有什么意义？或者理解有问题？ **

**Comment by answershuto** [comment]
@lzldemo  
dep也是每个被双向绑定的对象的闭包中会存在的，watcher也不止一个。依赖收集的时候，需要进行依赖收集的对象会被触发getter，然后把watcher存放在自己的dep中，这样当它发生变化的时候，会通知所有依赖的watcher，让他们用自身对应的update来修改视图。

**Comment by lzldemo** [comment]
这个过程看起来有点绕， 看了很多遍依然不太明白， 比如Dep.target的指向过程不太明白（data收集依赖时），还看到initComputed方法中， 计算属性会分别创建一个watcher，不确定 data收集依赖是不是共享一个watcher（绑定每个key时都通过depend把当前观察属性内的dep实例挂在Watcher上）；

**Comment by answershuto** [comment]
@lzldemo 再好好理理哈少年，我当时也想了很久～

**Comment by lzldemo** [comment]
@answershuto  感谢回复🙏！ 上午提的pr先关了吧， commit写的不规范

**Comment by answershuto** [comment]
@lzldemo OK～
