### ISSUE TITLE
请教一下：state 的watcher是如何发起的？

### ISSUE THREAD

**Issue by lzldemo** [answershuto/learnVue#15]
看到依赖是Watcher.get 设置Dep.target， 通过value = this.getter.call(vm, vm)完成收集依赖的过程， 但仍然没有搞明白state的Watcher是如何初始化的；
（动态设置Dep.target参看了这篇文章https://segmentfault.com/a/1190000010014281）

**Comment by answershuto** [comment]
Watcher初始化吗？有一个new Watcher的。

**Comment by lzldemo** [comment]
对的， 主要疑惑的是在哪里进行的初始化， 上午已经确定了， 是在mountComponent 中 vm._watcher = new Watcher(vm, updateComponent, noop) 对data中对属性发起检测并绑定的
在 2017年10月31日，上午9:34，染陌同学 <notifications@github.com<mailto:notifications@github.com>> 写道：

new
