### ISSUE TITLE
小白请教函数参数写法问题

### ISSUE THREAD

**Issue by lizhongzhen11** [answershuto/learnVue#16]
function initData(vm: Component){}这里的 vm: Component是什么意思啊，不像是解构赋值啊

**Comment by answershuto** [comment]
冒号后面的是类型

**Comment by lizhongzhen11** [comment]
这样啊，我以前没学过，尴尬，

**Comment by lizhongzhen11** [comment]
为什么会有这种方式呢。。。后面还有Array<String>,感觉这么像java的泛型啊。。。捂脸

**Comment by zhw2590582** [comment]
这是flow的类型验证而已，不属于js语法

**Comment by lizhongzhen11** [comment]
3Q，明白了
