### ISSUE TITLE
关于依赖收集的理解问题

### ISSUE THREAD

**Issue by notCoolBean** [answershuto/learnVue#28]
```js
Object.defineProperty(obj, key, {
        enumerable: true,
        configurable: true,
        get: ()=>{
            if (Dep.target) {
                /*Watcher对象存在全局的Dep.target中*/
                dep.addSub(Dep.target);
            }
        },
        set:newVal=> {
            /*只有之前addSub中的函数才会触发*/
            dep.notify();
        }
})
```
我这么理解的：关于大佬所说的例子中的如果text3改变了会不会触发视图更新问题关键点在于是不是触发get 方法 
还有就是 这个watch中有一个问题如果是三个数据都会触发视图更新的话 会触发三次get方法也就是说这时Dep.target都会有值而在这里没有对subs判断去重会不会有重复的watcher实例存在？这些疑问还望大佬能帮我解惑答疑 @answershuto

**Comment by photon-phalanx** [comment]
大概说一下自己的理解

这里的text3改变了会不会触发视图更新问题是针对上一节的内容说的
text3改变了自然会触发set，然后set里就做了cb，cb是render，所以就重新render了
依赖收集说的就是去找找到底有没有谁需要用到这个变量的，真的有需要的才会去做回调，否则数组空的啥都不做。
后面的说的没错，这里确实没有去重，这里只是一种原理理解罢了，不要抓细节啦……
在下一节就会看到，确实做了去重了
