### ISSUE TITLE
当data被observe后，在new render watch时触发watch的get求值，调用到pushTarget后，怎么就将这个watch添加到了subs中了？

### ISSUE THREAD

**Issue by marklbp** [answershuto/learnVue#34]
模版：<div id="app">{{test.a}}</div>

new Vue({
 data: {
  test: {a: 1}
},
el: "#app"
})

我通过浏览器断点逐行调试发现，在data被observe后，此时data下的__ob__.dep.subs集合为空数组，当执行Vue.prototype.$mount时new Watcher()，得到render watch调用watch.get()求值，这个get函数第一句pushTarget(watch)这一步后立马可以看到data下的__ob__.dep.subs下添加了这个render watch，而vuejs里watch是通过addSub添加到subs的，但此时并没有发现调用dep的addSub方法，关键的是这个时候没有到render那里去，所以依赖收集无从谈起，请教这个如何做到的？

**Comment by marklbp** [comment]
@answershuto

**Comment by beierweiwei** [comment]
@marklbp  new watcher的时候会对表达式求值，这个时候会调用data中的数据，同时watcher会将Dep.target设为自己，而data中的数据通过oberver中在get方法中会将Dep.target添加到dep中，这样就完成了依赖收集了。

**Comment by marklbp** [comment]
@beierweiwei 我知道new watcher的时候会求值，我的问题是在开始求值的时候，也就是调用watch.get()的第一句执行完pushTarget()后，你可以试着去看data下__ob__.dep.subs这数组里已经存放了对应watch，而这个时候并没有调用addSub方法也没有开始依赖收集，但是watch却被添加到subs数组了，这是我问题的疑点

**Comment by weisiwu** [comment]
依赖收集的原理是, 在值的 get 中埋入收集代码，在生成 watcher(依赖) 的代码中,调用值(get),将自己传进去，从而完成收集。

不知道我说的准不准确
