### ISSUE TITLE
【依赖收集】新建Watcher位置可能有误

### ISSUE THREAD

**Issue by LASkuma** [answershuto/learnVue#37]
大佬好！在[开始依赖收集](https://github.com/answershuto/learnVue/blob/master/docs/%E4%BE%9D%E8%B5%96%E6%94%B6%E9%9B%86.MarkDown#%E5%BC%80%E5%A7%8B%E4%BE%9D%E8%B5%96%E6%94%B6%E9%9B%86)章节顶部，新建Watcher的步骤被放在了Vue类的constructor里。然而在查阅源码后，我发现Watcher是由对应平台（Web或Weex）通过在最上层Vue实例的`$mount`函数中调用`mountComponent`而新建的。请问我的理解是否正确？谢谢！

**Comment by answershuto** [comment]
前两章讲了原理，没有严格按照源码，具体源码可以从第三章开始看

**Comment by LASkuma** [comment]
感谢大佬抽时间回答问题
